src/Horse.pas

Quando simulava 50 requisições simultaneas que levavam 3 segundos pra responder, ele dava erro de limite de conexoes maior que 32, mesmo configurando assim
`
API := THorse.Create(9000);
API.MaxConnections := 50;`
Resolvi o caso alterando no método THorse.Start de
`FHTTPWebBroker.MaxConnections := FMaxConnections;`
para 
`WebRequestHandler.MaxConnections := FMaxConnections;`

Alterar o MaxConnections default

---

src/Horse.Router.pas

if the "next" procedure is executed with any error, the "next" variable will not be set to nil, causing a memory leak. Now, with the "try finally" block, it didn't cause any memory leaks!

resolved: #26

---

src/Horse.Router.pas

Was ignoring the status code and error message when the middleware was throwing the exception and it was not being used in the 'Use' method.

A small correction in error handling

---

src/Horse.Constants.pas
src/Horse.pas

Opção para definir em qual endereço IP o servidor irá rodar, muito útil quando utilizado com servidor proxy.
Com proxy pode haver necessidade do app rodar somente em **localhost (127.0.0.1)**, não sendo necessário o mesmo está disponível em todos os endereços IPs da máquina.
**App:= THorse.Create('127.0.0.101', 9000);**

Opção para atribuir em qual endereço IP o servidor irá rodar

---

src/Horse.Core.pas

Se o middleware tiver path, estava sendo concatenado com o prefix..
Ele nunca era executado!

adjusted-middleware

---

src/Horse.Core.Group.Contract.pas
src/Horse.Core.Group.pas
src/Horse.Core.Route.Contract.pas
src/Horse.Core.Route.pas
src/Horse.Core.pas
src/Horse.pas
src/Web.WebConst.pas

I made some adjustments to allow the compilation and use of Horse in Delphi XE6.
As in the XE6 version Delphi does not have TMethodType, mtDelete and mtPath, I used a compilation directive verifying that if the compilation version is XE6, the Delete and Path methods will not be included in the compilation.
I performed tests on Delphi XE6 and 10.3.3 Rio

Settings for compilation in Delphi XE6

---

src/Horse.Core.Group.Contract.pas

Replace {$IF CompilerVersion > 27.0} with {$IF (defined(fpc) or (CompilerVersion > 27.0))}

{$IF CompilerVersion > 27.0} incompatible with lazarus

---

src/Horse.Core.RouterTree.pas

Quando utilizado dessa forma*, a criação do caminho do recurso está concatenando o prefix e o path sem a barra da URL ficando assim nesse exemplo:
http://localhost:9000/v1ping
A rotina Prefix remove o caractere '/' e quando chamado a função GetQueuePath a uma concatenação Prefix + Path.
* THorse.Routes.Prefix('v1/');
* THorse.Routes.RegisterRoute(TMethodType.mtGet, 'ping', GetPing);

Correção de bug ao utilizar Prefix junto RegisterRoute:

---

samples/delphi/console/Console.dpr

Pequeno ajuste no sample console para capturar os vazamentos de memória sem a necessidade de executar a aplicação via terminal

Report memory leaks

---

src/Horse.HTTP.pas

Implements a `RedirectTo` method for `THorseResponse`. It can be used when the developer wants the handler to send a redirection response. While it may not seem to be much useful at constructing APIs it's useful when constructing applications where the view layer is processed at backend and a full HTML response is commonly sent to client. With `RedirectTo` we can use a handler to process a POST request and then send the user to another page with the result of processing with a GET, a common standard for MVC or similar web frameworks.

Implement RedirectTo method for THorseResponse

---

src/Horse.Session.pas

Novas funcionalidades na classe THorseSessions:
- **TryGetSession:** Retorna verdadeiro ou falso se existe um objeto do tipo **TSessionClass** na lista de sessões, caso verdadeiro retorna a instância desse objeto. Função não gera exceção caso não exista a instância desse obejto.
- **Contains:** Retorna verdadeiro ou falso se existe um objeto do tipo **TSessionClass** na lista de sessões.

Melhorias na classe Horse.Session.THorseSessions

---

src/Horse.Commons.pas
src/Horse.Core.Param.Config.pas
src/Horse.Core.Param.Field.Brackets.pas
src/Horse.Core.Param.Field.pas
src/Horse.Core.Param.pas

Example:
http://localhost:9000/ping?test[eq]=1234&test[lt]=321&test[ne]=111
```
procedure GetPing(Req: THorseRequest; Res: THorseResponse; Next: TNextProc);
var
LLhsBracketType: TLhsBracketsType;
LPong: TJSONArray;
LJson: TJSONObject;
begin
THorseCoreParamConfig.GetInstance.CheckLhsBrackets(True);
LPong := TJSONArray.Create;
for LLhsBracketType in Req.Query.Field('test').LhsBrackets.Types do
begin
LJson := TJSONObject.Create;
LJson.Add(Format('test %s =',
[LLhsBracketType.ToString]) ,
Req.Query.Field('test').LhsBrackets.GetValue(LLhsBracketType));
LPong.Add(LJson);
end;
Res.Send(LPong.AsJSON);
end;
```

Add support to LHS Brackets

---

src/Horse.Core.Param.Field.pas
src/Horse.Core.Param.pas
src/Horse.Request.pas
tests/src/Console.dpr
tests/src/Console.dproj
tests/src/VCL.dpr
tests/src/VCL.dproj
tests/src/tests/Tests.Horse.Core.Param.pas

In Parameters Form-data to fetch the passed files we would have to make a loop in the property FWebRequest.Files. This implementation assigns the files passed in the form-data inside the ContentFields property and can be accessed as follows:
``` delphi
Req.ContentFields.Field('paramName').AsStream;
// or
Req.ContentFields.Field('paramName').SaveToFile('file.txt');
```

Add form-data file params in Req.ContentFields

---

src/Horse.Response.pas

Criado uma nova funcionalidade na classe THorseResponse igual a SendFile que passa um arquivo, nesse nova rotina SendFile é possível passar um Stream de um arquivo.
THorse.Get('export',
procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
var
lFileStream: TFileStream;
begin
lFileStream := TFileStream.Create('C:\horse\samples\delphi\vcl\Horse-SendFile.pdf', fmOpenRead);
try
Res.SendFile(lFileStream, 'Horse-SendFile.pdf', 'application/pdf');
finally
lFileStream.Free;
end;
end);
Testado
* Delphi
* Lazarus

Nova funcionalidade para envio de stream na classe THorseResponse

---

src/Horse.Exception.pas

- Adição do campo Hint na classe de exceção EHorseException, para descrever a solução do erro;
- Adição do método ToJSON para geração do JSON dos campos da classe EHorseException utilizado pelo **handle-exception**;
**ToJSON:**  O método ToJSON foi criado para gerar o JSON da classe EHorseException utilizado pelo  handle-exception, como é um método virtual pode ser sobrescrito e manipulado para gerar o JSON conforme a necessidade sem precisar de um PR para modificação.
Por Exemplo: Desta forma não foi preciso abrir um PR para o desenvolvimento do HashLoad para incluir o campo novo, simplesmente alterado o método ToJSON.
- Verificação MemoryLeaks: Ok
- Verificação da quebra de código: Sem quebra
- Compatibilidade Delphi/Lazarus: Mantido
- Dependência: …

Melhorias na classe EHorseException

---

src/Horse.Core.Param.Header.pas

```delphi
uses Horse, Web.HTTPD24Impl;
var
ApacheModuleData: TApacheModuleData;
exports
ApacheModuleData name 'apache_horse_module';
begin
THorse.DefaultModule := @ApacheModuleData;
THorse.HandlerName := 'apache_horse_module-handle';
THorse.Get('/ping',
procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
begin
Res.Send('pong: ' + Req.Headers.Field('CONNECTION').AsString);
end);
THorse.Listen;
end.
```

Fixed header reading in Apache for Delphi

---

src/Horse.Core.RouterTree.NextCaller.pas
src/Horse.Core.RouterTree.pas

Para registrar uma rota com REGEX, deve iniciar e fechar com parênteses.
Dentro do parênteses deve passar a instrução;
**NÃO FOI TESTADO NO LAZARUS, QUEM SOUBER COMO FAZER ISSO NO LAZARUS, PODE MEXER**
```delphi
uses
Horse;
begin
THorse.Get('/(discussion|page)/:id',
procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
begin
Res.Send('Hello - ID: ' + Req.Params.Items['id']);
end);
THorse.Get('/(\d{5})',
procedure(Req: THorseRequest; Res: THorseResponse; Next: TProc)
begin
Res.Send('Hello - ID: ' + Req.RawWebRequest.PathInfo);
end);
THorse.Listen(9000,
procedure(Horse: THorse)
begin
Writeln(Format('Server is runing on %s:%d', [Horse.Host, Horse.Port]));
Readln;
end);
end.
```

Added regex in router

---

src/Horse.Request.pas

#fix Issue #332 - Alterando a comparação de String.IsEmpty para igual a EmptyStr, para compatibilidade com Delphi 10 Seattle

#Fix Update Horse.Request.pas compatibilidade Delphi 10 Seattle.

---

src/Horse.Commons.pas
src/Horse.Core.Param.Field.Brackets.pas

Add new LHS bracket options for working with strings:
- Contains: %example%
- StartsWith: example%
- EndsWith: %example
`http://localhost:9000/ping?test[contains]=abc&test[startsWith]=def&test[endsWith]=ghi`
Based on: https://subscription.packtpub.com/book/web-development/9781800560635/8/ch08lvl1sec40/filtering-api-content

Add new LHS Brackets: Contains, StartsWith and EndsWith

---

src/Horse.Exception.pas

Compilation of `samples/lazarus/console/Console.lpr` with FPC fails at `Horse.Exception` unit, due to a semicolon before `Horse.Commons` in the uses clause, from the point of view of FPC.

Fix uses clause of Horse.Exception when FPC is defined

---

src/Horse.Exception.Interrupted.pas

When exception of this type is dispared in middleware JWT, don't show a message with a reason the exception.

Created a overload constructor with string parameter

---

src/Horse.Request.pas

Utilizando o windows, postman e Delphi Seattle.
Conteúdo do Body:
`{
"nome": "TIPOSEPARACAO",
"descricao": "Tipo de separação"
}`
Na api, na chegada do Request.Body:
`{ "nome": "TIPOSEPARACAO",'#$D#$A'    "descricao": "Tipo de separaÃ§Ã£o"'}`
Sugestão de correção no metodo Body do Horse.Request
`function THorseRequest.Body: string;
begin
{$IF CompilerVersion <= 31.0}
Result := TEncoding.UTF8.GetString(BytesOf(FWebRequest.RawContent));
{$ELSE}
Result := FWebRequest.Content;
{$ENDIF}
end;`

Na versão Seattle o Body do Request não esta reconhecendo caracteres especiais

---

src/Horse.Callback.pas
src/Horse.Commons.pas
src/Horse.Core.Files.pas
src/Horse.Core.Group.pas
src/Horse.Core.Param.Field.Brackets.pas
src/Horse.Core.Param.Field.pas
src/Horse.Core.Param.Header.pas
src/Horse.Core.Param.pas
src/Horse.Core.Route.pas
src/Horse.Core.RouterTree.NextCaller.pas
src/Horse.Core.RouterTree.pas
src/Horse.Core.pas
src/Horse.Exception.pas
src/Horse.Mime.pas
src/Horse.Provider.Console.pas
src/Horse.Request.pas
src/Horse.Response.pas
src/Horse.Rtti.pas
src/Horse.Session.pas
src/Horse.WebModule.pas

A limpeza e reorganização de units se trata de boas práticas. Trás muitas vantagens, como diminuição no tempo de compilação e no tamanho do arquivo final.

Limpeza e reorganização de units
