- src/Horse.Core.pas
> resolved: #30

- src/Horse.Router.pas
- Exceptions are now handled correctly. Before, error 500 was not displayed.
- A small improvement in the code in the GetQueuePath method.
> Improved exception handling and code improvement

- src/Horse.Core.Route.Intf.pas
- src/Horse.Core.Route.pas
- src/Horse.Core.pas
Enable multiple get and post methods without having to specify path again.
> Improvement Router Method

- README.md
Add Third Party Middleware for upload files to server
> New middleware for upload files

- src/Horse.Core.Group.Intf.pas
- src/Horse.Core.Group.pas
- src/Horse.Core.pas
- src/Horse.ISAPI.pas
- src/Horse.Router.pas
- src/Horse.WebModule.pas
- src/Horse.pas
**Prefix added**
**Group added**
> Added improvement - Prefix and Group

- src/Horse.Core.Route.Intf.pas
- src/Horse.Core.Route.pas
> Improvement Method Route All

- src/Horse.Core.pas
- src/Horse.Router.pas
- src/Horse.WebModule.pas
After the last change, there were some errors regarding the status code
> Correction of the status code

- src/Horse.Core.RouterTree.pas
- src/Horse.HTTP.pas
- src/Horse.Provider.FPCApacheApplication.pas
- src/Horse.Provider.FPCCGIApplication.pas
- src/Horse.Provider.FPCHTTPApplication.pas
- src/Horse.WebModule.pas
Removed the need to inform the module in the URI when compiled for Lazarus and some source code improvements.
> Some source code improvements.

- src/Horse.HTTP.pas
URL:  http://localhost:9000/?param1=abc%3D123&param2=zxy=987
Result:
> Adjusted QueryParams

- horsepkg.dpk
- samples/delphi/vcl/Horse.groupproj
- samples/delphi/vcl/VCL.dpr
- samples/delphi/vcl/VCL.dproj
- samples/delphi/vcl/uVCL.dfm
- samples/delphi/vcl/uVCL.pas
- src/Horse.Provider.Console.pas
- src/Horse.Provider.VCL.pas
- src/Horse.pas
Adicionado suporte a projeto VCL e exemplo de projeto.
> provider-vcl

- src/Horse.Core.Group.Contract.pas
- src/Horse.Core.Group.pas
> add-use-in-group

- samples/delphi/vcl/VCL.dproj
- src/Horse.Provider.VCL.pas
- src/Horse.pas
Correction in the HORSE_VLC compilation directive for HORSE_VCL.
> Correction to the build directive HORSE_VCL.

- src/Horse.Core.Route.pas
Replaced with {$IF (defined(fpc) or (CompilerVersion > 27.0))}
> {$IF(CompilerVersion > 27.0}} incompatible with lazarus

- src/Web.WebConst.pas
replaced with {$IF (defined(fpc) or (CompilerVersion > 27.0))}
> {$IF  (CompilerVersion > 27.0)} incompatible with lazarus

- samples/lazarus/daemon/daemon.lpi
- samples/lazarus/daemon/daemon.lpr
- samples/lazarus/daemon/daemon.lps
- src/Horse.pas
- src/horse.provider.fpcdaemon.pas
Foi implementado um novo provider e o exiemplo de como usar ele.
> Novo provider Daemon  e exemplo para Lazarus.

- src/Horse.HTTP.pas
Initialize params on demand.
Add Web.ReqMulti uses to register the formdata parse.
> Initialize params on demand.

- src/Horse.Provider.Abstract.pas
- src/Horse.Provider.Console.pas
Implementing callback to be called when stopping listen
> Callback StopListen

- README.md
Middleware to serve a directory of static files.
> Add Middleware horse-server-static

- README.md
Update README.md
New middleware for exception logging in HORSE
> New middleware for exception logging in HORSE

- src/Horse.Commons.pas
- src/Horse.HTTP.pas
- src/Horse.Provider.Console.pas
> Implementação da classe THorseSessions

- README.md
Adicionando um Middlewares de Apoio a Trabalhos com JSON
> Adicionando um Middlewares de Apoio a Trabalhos com JSON

- samples/delphi/apache/Apache.dproj
- samples/delphi/console/Console.dproj
- samples/delphi/daemon/Daemon.dproj
- samples/lazarus/fastcgi/FCGI.lpi
Move Search Path to All Configurations to Apache Sample fixing compilation error for Win32
Replace Search Path Console Sample fixing compilation erro when source is not in 'horse' folder, like 'horse-master'
Add Search Path in Daemon Sample
Add Search Path in FastCGI Lazarus Sample
> Review Search Path Samples

- src/Horse.Core.Param.Header.pas
- src/Horse.HTTP.pas
- src/Horse.Rtti.pas
> Horse Headers

- samples/delphi/console/Console.dpr
- samples/delphi/console/Console.dproj
- samples/lazarus/console/Console.lpr
- samples/lazarus/console/Console.lps
- src/Horse.Core.Param.Header.pas
- src/Horse.Core.Param.pas
- src/Horse.Core.RouterTree.pas
- src/Horse.HTTP.pas
- src/Horse.pas
- tests/src/Console.dpr
- tests/src/Console.dproj
- tests/src/VCL.dpr
- tests/src/VCL.dproj
- tests/src/controllers/Controllers.Api.pas
- tests/src/tests/Tests.Api.Console.pas
- tests/src/tests/Tests.Api.Vcl.pas
- tests/src/tests/Tests.Commons.pas
- tests/src/tests/Tests.Horse.Core.Param.pas
Core Param Class
Unit Tests Param Class
Correct MemoryLeaks in Test Projects
> Horse Core Param

- src/Horse.Core.Param.pas
- tests/src/tests/Tests.Horse.Core.Param.pas
Ignore Case Params in Header, Query and Path params
> Ignore Case Params

- samples/delphi/console/Console.dpr
- src/Horse.Core.RouterTree.pas
Refactor Sample to ReportMemoryLeak
> Report Memory Leak Sample

- src/Horse.Core.Group.Contract.pas
- src/Horse.Core.Group.pas
- src/Horse.Core.Param.Field.pas
- src/Horse.Core.Param.pas
- src/Horse.Core.Route.Contract.pas
- src/Horse.Core.Route.pas
- src/Horse.Core.RouterTree.pas
- src/Horse.Core.pas
- src/Horse.HTTP.pas
- src/Horse.pas
- tests/src/Console.dpr
- tests/src/Console.dproj
- tests/src/VCL.dpr
- tests/src/VCL.dproj
- tests/src/tests/Tests.Api.Console.pas
- tests/src/tests/Tests.Api.Vcl.pas
- tests/src/tests/Tests.Horse.Core.Param.pas
- Class Param.Field
- Class to config Field Params
> Config Field Params

- src/Horse.Core.pas
- src/Horse.Response.pas
> Added new method All

- README.md
Starting Lazarus compatibility from contribuition @andre-djsystem
> Starting Lazarus compatibility

- src/Horse.Request.pas
Read Param Form Data in Delphi Berlin, Seattle and previous
> Read Param Form Data in Delphi Berlin, Seattle and previous

- src/Horse.Response.pas
- Set File position to zero;
- Optional to send filename;
> Set File position to zero

- src/Horse.Exception.pas
- Ajuste para compilação Lazarus.
- Referente: https://github.com/HashLoad/horse/pull/321
> HotFix: Ajuste para compilação Lazarus.

- src/Horse.Exception.pas
Ajustado o método ToJson para retornar o result do ToJsonObject.
> Adicionado a property Detail e adicionado o método ToJsonObject

- src/Horse.Core.Param.Header.pas
Solução para:
https://github.com/HashLoad/horse/issues/338
TWebResponse no lugar de TApacheRequest com condicional na compilação.
> Correção na opção Apache Module

- README.md
Tested it on Delphi 12 and works without any issues.
> Added Support for "Delphi 12 Athens" in Update README.md
